### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSPAP1982** [Drew-Pappas/itunes_CLI_search#1]
hello my friend!!!tell me please this is for searching music...songs and albums from itunes?and if yes,please could you make a web version?I am begging you!!!

**Comment by Drew-Pappas** [comment]
Unfortunately this is a rudimentary command line level search right now. It returns 50 results and classifies those results into Movie, Song, or Media objects and allows you to preview the object in browser. I suggest taking a look at the API docs for Itunes for more information as it wasn't too difficult to create in Python.
